trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: 'BuildConfiguration'
    value: 'Release'

steps:
  - script: |
      echo "Installing PHP..."
      sudo apt-get update
      sudo apt-get install -y php

  - script: |
      echo "Installing Composer..."
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php --quiet
      php -r "unlink('composer-setup.php');"
      sudo mv composer.phar /usr/local/bin/composer

  - script: |
      echo "Installing project dependencies..."
      composer install

  - script: |
      echo "Running PHP script..."
      php index.php

